UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, '[MOD]') = 0 THEN ' [COLOR_RED][MOD][ENDCOLOR]' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGEGROUP_SCIENCE_NAME' AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, '[MOD]') = 0 THEN ' [COLOR_RED][MOD][ENDCOLOR]' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGE_SCIENCE_2_CHAPTER_CONTENT_TITLE' AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, '[MOD]') = 0 THEN ' [COLOR_RED][MOD][ENDCOLOR]' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGEGROUP_CULTURE_NAME' AND Language = 'en_US' ;
UPDATE LocalizedText SET Text = Text || CASE WHEN INSTR(Text, '[MOD]') = 0 THEN ' [COLOR_RED][MOD][ENDCOLOR]' ELSE '' END WHERE Tag = 'LOC_PEDIA_CONCEPTS_PAGE_CULTURE_2_CHAPTER_CONTENT_TITLE' AND Language = 'en_US' ;

-- ('', '', 'en_US'),

INSERT OR IGNORE INTO LocalizedText 
(Tag, Text, Language) VALUES
('LOC_PEDIA_CONCEPTS_PAGE_SCIENCE_2_CHAPTER_CONTENT_PARA_2', '[COLOR_RED]\/ \/ \/ \/ \/ \/ \/ \/ [from the mod "DB [ICON_Science]Yield Tweaks[ICON_Culture]"] \/ \/ \/ \/ \/ \/ \/ \/[ENDCOLOR][NEWLINE][NEWLINE]Your civilization''s science/culture output gets a bonus when you are researching a tech/civic that you''ve seen in another civilization. Consider: the most helpful knowledge for researching something like, say, nuclear fission or democracy, would be knowing that it exists and seeing it in action somewhere in the world. And seeing it in different nations gives you more ways to learn about it.[NEWLINE][NEWLINE]The way the mod works is like this... If you''ve met all the civilizations and they all have the tech/civic you''re researching, your science/culture is boosted by 200% (i.e. tripled) while researching this tech/civic. That''s the max. When every other nation has Pottery and you see it in marketplaces all over the world, it wouldn''t be too tough to figure out the technology for yourself.[NEWLINE][NEWLINE]Now if only half the other civs have the tech/civic you''re researching, the boost is half as much (+100%)[NEWLINE]A quarter of your opponents ==>> +50%[NEWLINE]One out of 8 opponents ==>> +25%[NEWLINE]If no one has it yet ==>> no bonus[NEWLINE][NEWLINE]Furthermore, the bonus that a civ gives you is 25% higher for each level of Diplomatic Visibility you have on their civilization. (Diplomatic Visibility comes from delegations, embassies, traders, spies, alliances, and the Printing Press technology.) So if 1 opponent out of 8 has the tech/civic you''re researching, and you have Open level visibility on them, you would get a +37.5% bonus instead of +25%.' , 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CULTURE_2_CHAPTER_CONTENT_PARA_2', '[COLOR_RED]\/ \/ \/ \/ \/ \/ \/ \/ [from the mod "DB [ICON_Science]Yield Tweaks[ICON_Culture]"] \/ \/ \/ \/ \/ \/ \/ \/[ENDCOLOR][NEWLINE][NEWLINE]Your civilization''s science/culture output gets a bonus when you are researching a tech/civic that you''ve seen in another civilization. Consider: the most helpful knowledge for researching something like, say, nuclear fission or democracy, would be knowing that it exists and seeing it in action somewhere in the world. And seeing it in different nations gives you more ways to learn about it.[NEWLINE][NEWLINE]The way the mod works is like this... If you''ve met all the civilizations and they all have the tech/civic you''re researching, your science/culture is boosted by 200% (i.e. tripled) while researching this tech/civic. That''s the max. When every other nation has Pottery and you see it in marketplaces all over the world, it wouldn''t be too tough to figure out the technology for yourself.[NEWLINE][NEWLINE]Now if only half the other civs have the tech/civic you''re researching, the boost is half as much (+100%)[NEWLINE]A quarter of your opponents ==>> +50%[NEWLINE]One out of 8 opponents ==>> +25%[NEWLINE]If no one has it yet ==>> no bonus[NEWLINE][NEWLINE]Furthermore, the bonus that a civ gives you is 25% higher for each level of Diplomatic Visibility you have on their civilization. (Diplomatic Visibility comes from delegations, embassies, traders, spies, alliances, and the Printing Press technology.) So if 1 opponent out of 8 has the tech/civic you''re researching, and you have Open level visibility on them, you would get a +37.5% bonus instead of +25%.' , 'en_US') ;
